/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/*******************************************************************************
  This source file has NOT been generated by the MHC
 *******************************************************************************/

/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */

// *****************************************************************************
// *****************************************************************************
// Section: Included Files 
// *****************************************************************************
// *****************************************************************************
#include <stdlib.h>
#include <stdio.h>
#include "game.h"
#include "UART.h"

#define TIMER_CLOCK_FREQ    (100000000)
#define SLOW_PERIOD         (TIMER_CLOCK_FREQ/(256 * 8))

// *****************************************************************************
// *****************************************************************************
// Section: Global Data Definitions
// *****************************************************************************
// *****************************************************************************



// *****************************************************************************
// *****************************************************************************
// Section: User Functions
// *****************************************************************************
// *****************************************************************************

// Comment a function definition and leverage automatic documentation 
/**
  <p><b>Function:</b></p>

  <p><b>Summary:</b></p>

  <p><b>Description:</b></p>

  <p><b>Remarks:</b></p>
 */
// TODO Insert function definitions (right here) to leverage live documentation

int Get_Guess(void) {
    char c;
    int n = 0, done = 0;

    while (1) {
        c = UART4_getc();
        UART4_putc(c); // echo back character
        if ((c >= '0') && (c <= '99')) {
            n *= 10;
            n += c - '0';
        } else {
            if (c == '\r')
                return n;
            else
                return ILLEGAL_CHAR;
        }
    }
}

void InitTimer2(void) {
    T2CON = 0; // clear timer settings to defaults
    T2CONbits.TCKPS = 7; // divide clock by 256 with prescaler
    TMR2 = 0;
    PR2 = SLOW_PERIOD;

    IPC2bits.T2IP = 3; // Priority level 3
    IPC2bits.T2IS = 0;

    IFS0bits.T2IF = 0; // Clear interrupt request flag
    IEC0bits.T2IE = 1; // Enable timer interrupt
}

void GuessingGame(void) {
    int guess, number, guesses_left = 7, won = 0;
    static int num_won = 0, num_lost = 0;
    char buffer[80];
    while (1) {
        UART4_puts("\r\nWelcome to the guessing game!\r\n");
        UART4_puts("\r\nTake Guess\r\n");
        T2CONbits.ON = 1; //turn timer 2 on


        char charValue;
        for (guesses_left=7; guesses_left > 0; guesses_left--) {

            guess = Get_Guess();
            if (guesses_left == 7) {
                number = TMR2;
                T2CONbits.ON = 0; //turn timer 2 off

                number = ((number)*0.002);
            }

            if (guess == number) {
                UART4_puts("\r\nSuccess!\r\n");
                num_won++;
                break;
            }
            if (guess > number)
                UART4_puts("\r\ntoo high\r\n");
            if (guess < number)
                UART4_puts("\r\ntoo low\r\n");
            if (guesses_left == 1) {
                num_lost++;
                UART4_puts("\r\nTry next time\r\n");
                sprintf(buffer, "\r\nThe number was: %d", number);
                UART4_puts(buffer);
                UART4_puts("\r\n");
                sprintf(buffer, "\r\"Wins: %d\r\n", num_won);
                UART4_puts(buffer);
                sprintf(buffer, "\r\"Losses: %d\r\n", num_lost);
                UART4_puts(buffer);
                break;
            }
            UART4_puts("\r\nguesses left!:");
            charValue = guesses_left - 1 + '0';
            UART4_putc(charValue);
            UART4_puts("\r\n");
        }
    }
}

